### PR TITLE
mitigating effects of Moose PR #28570 (check block-restriction in duplicateVariableCheck)

### LINKED ISSUE #456: Effects of Moose PR #28570: check block-restriction in duplicateVariableCheck
With the PR https://github.com/idaholab/moose/pull/28570 for Moose the function `duplicateVariableCheck` gets more strict: The new behaviour enforces that the block restriction matches or is permitted if the very same variable is requested multiple times.

Unfortunately, once merged this change for Moose will make at least one example Mastodon fail (`Mastodon/examples/ex05a.ex05a`)

### PR DESCRIPTION
**Pull request by jmeier**
With the PR https://github.com/idaholab/moose/pull/28570 for Moose the function `duplicateVariableCheck` gets more strict: The new behaviour enforces that the block restriction matches or is permitted if the very same variable is requested multiple times.

Unfortunately, once merged this change for Moose will make at least one example Mastodon fail (`Mastodon/examples/ex05a.ex05a`). This PR aims to mitigating this effect.

closes #456

### CODE REVIEW

**Comment by jmeier** [comment]
@GiudGiud

**Comment by jmeier** [comment]
With this fix, three more tests fail:

```
test:mastodonblock/outputs.variable_action .................................................... FAILED (CRASH)
test:mastodonblock/combined.mastodon_block_actions ............................................ FAILED (CRASH)
test:mastodonblock/combined.mastodon_block_actions_2D ......................................... FAILED (CRASH)
```

But I'm not sure this is due to https://github.com/idaholab/moose/pull/28570. All three tests crash with the same error message:
```
*** Warning, This code is deprecated and will be removed in future versions:
Please use the addAuxVariable(var_type, var_name, params) API instead
Stack frames: 15
0: libMesh::print_trace(std::ostream&)
1: void moose::internal::mooseDeprecatedStream<ConsoleStream const, char const (&) [70]>(ConsoleStream const&, bool, bool, char const (&) [70])
2: FEProblemBase::addAuxVariable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, libMesh::FEType const&, std::set<unsigned short, std::less<unsigned short>, std::allocator<unsigned short> > const*)
3: MastodonOutputsAction::addStressStrainAuxVariables()
```

**Comment by jmeier** [comment]
With [a48e047](https://github.com/idaholab/mastodon/pull/457/commits/a48e04745cc982ce4f9c14740658ce297b44ed2e) the checks are all green on my machine. 

Please carefully check what have been done to poor Mastodon...

**Comment by GiudGiud** [comment]
This seems fine to me however the deprecation warning is likely not the problem. I ll try the patch locally

**Pull request merged**
