### PR TITLE
use static validParams function

### PR DESCRIPTION
**Pull request by lynnmunday**
I'm having trouble converting over the templated layered material.

ref #292

### CODE REVIEW

**Comment by somu15** [comment]
@lynnmunday So, when you use this for ComputeElasticIsotropicTensorSoil and ISoil, you are having build errors?

Also, you mentioned in your commit that this is not applicable to materials. The above two are material classes.

**Comment by lynnmunday** [comment]
This commit doesn't remove the templating on the materials validParams.   So this one works and I will work on the materials in a seperate commit

**Comment by lynnmunday** [comment]
can you make me a developer so that it will automatically run tests for me

**Comment by somu15** [comment]
@cbolisetti Can you please make Lynn a developer?

**Comment by cbolisetti** [comment]
@lynnmunday I added you to the developers' group a few days ago. Thanks for doing this. Is there anything else to be done here?

**Comment by lynnmunday** [comment]
There is a little left to do with a material.  I was going to ask Som to look at with me.  I didn't know how it worked.  We're not supposed to merge this until someone finishes some AD work in moose.

**Comment by lynnmunday** [comment]
If these pass, this can be merged.  This updates all InputParamters that are currently in mastodon to static.

**Pull request merged**
