### PR TITLE
Changes to theory manual, additions to user and examples manuals #3

### PR DESCRIPTION
**Pull request by sveerara**
Continuation of documentation work by Ozgun.

### CODE REVIEW

**Comment by sveerara** [comment]
@aeslaughter, the documentation and examples are passing all tests. But the images are not showing up in the user and examples manual. I have added the images corresponding to these two manuals are included in the commit. But I am not sure whether they are in git lfs or the normal git repository.

**Comment by aeslaughter** [comment]
I will take a look.

**Comment by aeslaughter** [comment]
@sveerara FYI, we are not using gitlfs anymore it was too much trouble. For mastodon we are just going to try to keep the image sizes to a minimum. If they start to add up we will create a media submodule.

**Comment by aeslaughter** [comment]
This is contained in #76.

**Pull request closed without merging**
