### PR TITLE
Sqa

### PR DESCRIPTION
**Pull request by cbolisetti**
Addressing CAs 2022-1782 and 2022-1784 on SQA

### CODE REVIEW

**Review by cticenhour — COMMENTED** [review]
What you have here looks good from an SQA perspective. There are still missing entries in the RTM. Did you intend to fix those up here as well?

**Comment by cbolisetti** [comment]
> What you have here looks good from an SQA perspective. There are still missing entries in the RTM. Did you intend to fix those up here as well?

Oops, looks like I missed updating the RTM. Thanks for pointing it out! Fixed it now..hopefully its good to go.

**Comment by cbolisetti** [comment]
@cticenhour this is good to go now. Can you please review and merge if its ok?

**Review by cticenhour — APPROVED** [review]

**Comment by cticenhour** [comment]
@cbolisetti I am not authorized to merge into MASTODON, but I'll put out a call to the @idaholab/mastodon-admin group to see if one of them can!

**Comment by cticenhour** [comment]
Ah - GitHub decided to wait to update until after I hit "comment". Nice 😅 Sorry for the spam all!

**Comment by cbolisetti** [comment]
> @cbolisetti I am not authorized to merge into MASTODON, but I'll put out a call to the @idaholab/mastodon-admin group to see if one of them can!

No worries, I just closed it. I just assume you can do everything @cticenhour :))

**Pull request merged**
