### PR TITLE
Rename heat conduction MOOSE module to heat transfer

### PR DESCRIPTION
**Pull request by GiudGiud**
https://github.com/idaholab/moose/pull/25585

### CODE REVIEW

**Comment by lindsayad** [comment]
This will need black bear fixed first

**Comment by GiudGiud** [comment]
yup. same as Grizzly.
Who else than @bwspenc can merge in blackbear

**Review by lindsayad — APPROVED** [review]

**Comment by bwspenc** [comment]
@GiudGiud sorry I missed the notification about this -- looks like you got BlackBear taken care of. Feel free to reach out to me through Slack or Teams if I don't see the notification from GitHub. All the noise of the GitHub notifications tends to make it easy to miss urgent things.

**Comment by GiudGiud** [comment]
no worries.

I would like a list of the people able to merge / on the CCB for every application. I dont think that exists

**Comment by GiudGiud** [comment]
@lindsayad

**Pull request merged**
