### PR TITLE
Tighten tolerance for test that fails after compiler change

### PR DESCRIPTION
**Pull request by aeslaughter**
(refs #183)

### CODE REVIEW

**Comment by aeslaughter** [comment]
I was just trying to see if I could improve these quickly, I think there is more work do be done. Do you really need to test so many timesteps?

**Comment by cbolisetti** [comment]
I'm still surprised this is failing with such tight tolerance. We might be able to reduce the number of time steps. My moose/mastodon are broken right now and Im not sure why. I'll take another look at it later.

**Comment by aeslaughter** [comment]
Perhaps the timestep tolerance is the real culprit.

**Comment by aeslaughter** [comment]
This can be re-opened when needed.

**Pull request closed without merging**
