### PR TITLE
Fixing test tolerance

### PR DESCRIPTION
**Pull request by somu15**
Fixing test tolerance
closes #408

### CODE REVIEW

**Comment by somu15** [comment]
@cbolisetti Can you please merge this if the tests pass? @fdkong needs to update libmesh and this test is causing tolerance issues. Thanks!

**Comment by somu15** [comment]
@fdkong I increased the abs_tol and tightened the rel_tol. Is this want you want?

**Comment by fdkong** [comment]
I would like to make the test more robust ...

I am checking now

**Comment by fdkong** [comment]
@somu15  Do you know why we have mesh in this way?

```
[Mesh]
  type = GeneratedMesh
  dim = 3
  nx = 1
  ny = 1
  nz = 20
  xmin = 0.0
  xmax = 25.0
  ymin = 0.0
  ymax = 25.0
  zmin = 0.0
  zmax = 5000.0
[]
```

In other words, we do not have really have any interior nodes, and what are we solving for? Everything is on boundary

**Comment by fdkong** [comment]
> May be there are interior nodes in the z direction?

There are no  interior nodes.  Apply PBCs generate some unknowns

**Review by lindsayad — APPROVED** [review]

**Pull request merged**
