### PR TITLE
Extending VPPs to vectors of nodes and boundaries

### PR DESCRIPTION
**Pull request by cbolisetti**
This PR is to extend the `ResponseHistoryBuilder`, `ResponseSpectraCalculator` and `HSICalculator` to vectors of nodes and boundaries. Currently, these VPPs are limited to one node. 

As of now, `ResponseHistoryBuilder` has been extended, but it fails for parallel processing.

### CODE REVIEW

**Comment by cbolisetti** [comment]
@aeslaughter please take a look, when you get a chance.

**Comment by aeslaughter** [comment]
@cbolisetti I am working on this now.

**Comment by aeslaughter** [comment]
@sveerara Could you review and merge this please, I contributed and won't be here next week.

**Comment by sveerara** [comment]
@aeslaughter, sure I will review this early next week.

**Comment by cbolisetti** [comment]
@sveerara thanks. I think this will finally be helpful and is hopefully used more.

**Pull request merged**
