### PR TITLE
Verification for ISoil Backbone Curves

### PR DESCRIPTION
**Pull request by crswong888**
As part of the Verification and Validation for MASTODON project, I am creating documentation for some ISoil tests. First I restructured the `doc/content/sqa` directory to separate out different types of V&V docs, e.g., `sqa/kernels/time_integration`, or `sqa/materials/isoil`. I then began creating new pages for verification of the different types of backbone curves. My general approach for these docs has been to solve the backbone curve analytically and then superimpose the stress/strain curves output by MASTODON to verify that they match.  I will continue to develop this PR, but please provide any and all feedback on the work I have done so far: `darendeli.md`, `gqh.md`, and `user_defined.md`.

Also, in my `darendeli.md` file, I've commented out an attempt at using plotly for the superimposed chart. I have found no issue with including two distinct data sets in a chart, so long as they both have the same X data points. However, if the X points are different (even if they are in the same range), then it seems that plotly fails at this. Instead I have simply included screenshots of charts containing the data, but I think if there was someway to make these charts using plotly then that would be much better since plotly is interactive online.

### CODE REVIEW

**Comment by sveerara** [comment]
@crswong888, looks like the precheck is failing because the commits don't have issue number at the end. Please add the issue number #228 at the end of the commit messages.

**Comment by crswong888** [comment]
Done.

**Comment by permcody** [comment]
If you lead your commit with [WIP] it won't be tested. I'm assuming however that you *do* want this PR tested?

**Comment by crswong888** [comment]
No it doesn't need to be fully tested at this point. I will be continuing to develop this PR until the end of the summer. My purpose for starting this PR early is so that people may comment on the documentation I have done so far. 

I suppose I could make this a full PR and go through all the testing, and simply open a second PR at the end of the summer with the rest of my work. What do you suggest?

**Comment by sveerara** [comment]
Ah I see. Either way works fine. I will look through the documentation later today.

**Comment by crswong888** [comment]
When I clicked the "visit the site here" link, it doesn't look right. None of the links at the top are visible, although this is not an issue when I run './moosedocs.py build --serve' on my local machine.

**Comment by crswong888** [comment]
Actually, this appears to be an issue for the [official MASTODON webpage](https://www.mooseframework.org/mastodon/).

**Comment by crswong888** [comment]
On my latest commit, I have consolidated all of my individual I-Soil V&V reports into one master report using the `!include` function. Also, since everything is on one page now, I cut out everything that was redundant between the markdown pages. I will continue to develop more ISoil V&V, but everything will be included in the master report from now on.

**Comment by crswong888** [comment]
My last commit created a new test that I will use for pressure dependent strength V&V documentation. I also edited the `HYS_pressure_dependent_stiffness.i` test to test the stiffness modification, since previously, it was actually testing strength. Finally, I modified the `tests` file to include the new test, and I changed the test for stiffness to a regular `type = Exodiff` test. Before, it seemed to be testing for an error if the user specified `b_exp = 0`, but not only does this error not occur, it's unnecessary. However, I have observed that if all three: `a0`, `a1`, and `a2` are set to zero, then the solver will not converge. If anything, there should be an error for this case.

**Pull request closed without merging**
