### PR TITLE
Site seismic risk updating example #243

### PR DESCRIPTION
**Pull request by somu15**
We are evaluating the seismic risk of collapse of a nuclear facility using old and new seismic hazard curves. Following are the sections in the documentation of this example:

1. Introduction

2. Methodology for risk updating in light of new seismic hazard
 2.1 Seismic hazard analysis and re-analysis
 2.2 Seismic fragility evaluation
 2.3 Event and fault trees for risk evaluation

3. Results
 3.1 Seismic hazard
 3.2 Fragility analysis
 3.3 Risk analysis

4. Conclusions and future recommendations

### CODE REVIEW

**Comment by cbolisetti** [comment]
@somu15 looks like you pushed the wrong files

**Comment by somu15** [comment]
> @somu15 looks like you pushed the wrong files

@cbolisetti I now uploaded the right files. Let me know if any changes are required.

**Comment by cbolisetti** [comment]
> > @somu15 looks like you pushed the wrong files
> 
> @cbolisetti I now pushed the right files. Let me know if any changes are required.

@somu15 I dont see the example. Please update the example index file as well, so that it shows up on the examples list.

**Comment by cbolisetti** [comment]
@somu15 I changed the example to mostly include MASTODON stuff. Please review and suggest changes.

**Comment by cbolisetti** [comment]
@somu15 looks like you force pushed and replaced my commits. You need to rebase your branch with my commits and push it without a -f

**Comment by somu15** [comment]
@cbolisetti Thank you for pointing this. I now rebased to your branch and then made changes before pushing. Please let me know if any changes are required.

Also, should the following files be a part of this commit?

 examples/ex08/gnf_2006_results/approach_2/results.csv
 examples/ex08/gnf_2015_results/approach_2/results.csv
 examples/ex08/risk_calc.ipynb

If not I can remove them.

**Comment by cbolisetti** [comment]
@hoffwm please take a look at the updated example after the tests finish. If you're good with it, can you approve the PR? We need at least one approver to merge.

**Pull request merged**
