### PR TITLE
Updated test to use SamplerTransientMultiApp

### PR DESCRIPTION
**Pull request by jiangwen84**
ref#198

### CODE REVIEW

**Comment by jiangwen84** [comment]
@permcody Does this look good? Did I miss anything?

**Comment by permcody** [comment]
That's it!

**Comment by permcody** [comment]
Oh, except I bet you'll need to update the submodule or this won't build.

**Comment by permcody** [comment]
You need to push the moose submodule update. Are you familiar with that process?

**Comment by jiangwen84** [comment]
@permcody I am not familiar with that process. Could you let me know what I should do? thanks!

**Comment by permcody** [comment]
In mastodon, make sure you've inited and checked out the MOOSE submodule:

cd mastodon
git submodule update --init

Now go into MOOSE and checkout the branch with your fix (currently "next")

cd moose
git fetch origin
git co next
git rebase

Now go back into mastodon and commit

git commit -a -m "Update MOOSE submodule"

and push!

git push origin <my_branch>

**Comment by jiangwen84** [comment]
@permcody thanks!

**Pull request merged**
