### PR TITLE
increase floor in exodiff for new compilers with conda build 

### PR DESCRIPTION
**Pull request by lynnmunday**
ref #307
I checked the exodiff -summary for these exodiff files and the
floor I put in is still small compared to the max values for the
variables that were diff'ing

### CODE REVIEW

**Comment by lynnmunday** [comment]
@hoffwm @cbolisetti   I updated the exodiff command for the failing conda build tests

**Comment by cbolisetti** [comment]
Oh man, all of our docs are failing, not sure why.

**Comment by lynnmunday** [comment]
> Oh man, all of our docs are failing, not sure why.

I think this is something Stephanie is working on to bring grizzly and blackbear into sqa compliance.  I don't know how to fix it.

**Comment by cbolisetti** [comment]
@hoffwm can you please review this?

**Pull request merged**
